[package]
name = "mini-pd"
version = "0.1.0"
authors = ["Jay Lee <BusyJayLee@gmail.com>"]
edition = "2018"

[dependencies]
kvproto = { git = "https://github.com/busyjay/kvproto", branch = "release-5.0-mini-pd" }
grpcio = "0.9.0"
raft = "0.6.0"
protobuf = "2.7.0"
